var miNumero = 5;
miNumero = 10 + 10;
miNumero = 2.5;
console.log(miNumero);
var booleano = false;
booleano = true;
console.log(booleano);
var encendido;
encendido = true;
console.log(encendido);
console.log('Encendido es:', encendido);
console.log('Encendido es:', { encendido: encendido });
encendido = true && false;
encendido = true && true;
encendido = false && true;
encendido = false && false;
console.log('Resultado de encendido:', encendido);
var normal = 'hola';
normal = 10;
normal = true;
normal = 11.11;
console.log('Normal:', normal);
