"use strict";
let normalx = 'hola';
normalx = 10;
normalx = true;
let usuario = 20;
console.log(normalx);
let nombre = 'Greys';
nombre = 'Alexa';
console.log(nombre);
let value;
console.log(value);
value = true;
value = 10;
value = 'holiwis';
value = [];
value = {};
value = Math.random;
value = null;
value = undefined;
console.log(value);
let miValor;
console.log("Tipo unknown", miValor);
let value1 = miValor;
let value2 = miValor;
//let value3: boolean = miValor;
const edad = 20;
console.log('Mi edad es:', edad);
console.log('Mi edad es:' + edad);
const sueldo = 123.456;
const total = Number('123'); //cast
console.log('Sueldo: ', sueldo);
console.log('Total: ', total);
const personaje = 'Jake el perro';
const otroPersonaje = "Fin el humano";
const otroOtroPersonaje = `Princesa grumosa y ${personaje}`;
console.log(otroOtroPersonaje);
const heroe = "Spiderman's House";
console.log(heroe);
console.log(heroe.toUpperCase());
let vengador;
vengador = 'Ironman';
console.log(vengador.charAt(4).toUpperCase());
vengador = 150.55;
//Redondeo a un decimal
console.log('El redondeo de 150.55 a 1 decimal es:', vengador.toFixed(1));
console.log(vengador.toFixed(1));
console.log(vengador.toFixed(1));
